server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8082/realms/digitalhouse
        registration:
          api-gateway-registration:
            provider: api-gateway-service
            client-id: gateway
            client-secret: pTGLI8eizjd5FXRBXBQTaEWMBzXIRVdz
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bills
          uri: http://localhost:8080
          predicates:
            - Path=/bills/**
